---
- name: Install and configure isc-dhcp-server and update iptables
  hosts: localhost
  become: true
  tasks:
    - name: Install isc-dhcp-server
      apt:
        name: isc-dhcp-server
        state: present

    - name: Install 50-cloud-init.yaml
      template:
        src: 50-cloud-init.yaml.j2
        dest: /etc/netplan/50-cloud-init.yaml
        owner: root
        group: root
        mode: '0644'
      vars:
        - wifi_bearden_password: "{{ENV_WIFI_PASSWORD}}"
      notify:
      - Apply Netplan

    - name: Update dhcpd.conf
      template:
        src: dhcpd.conf.j2
        dest: /etc/dhcp/dhcpd.conf
        owner: root
        group: root
        mode: '0644'
      vars:
        - dhcp_domain_name: "cluster.home"
      notify:
        - Restart DHCP Server

    - name: Set INTERFACES to eth0
      lineinfile:
        path: /etc/default/isc-dhcp-server
        line: 'INTERFACES="eth0"'
        state: present
        backup: yes
      notify:
        - Restart DHCP Server

    - name: Rename hostname to node-1
      hostname:
        name: node-1

    - name: Create k8s.conf for sysctl
      template:
        src: modules.k8s.conf.j2
        dest: /etc/modules-load.d/k8s.conf
        owner: root
        group: root
        mode: '0644'

    - name: Create sysctl.d k8s.conf file
      template:
        src: sysctl.k8s.conf.j2
        dest: /etc/sysctl.d/k8s.conf
        owner: root
        group: root
        mode: '0644'
      notify:
        - Apply sysctl settings

    - name: Enable IP forwarding
      ansible.builtin.lineinfile:
        path: /etc/sysctl.conf
        line: 'net.ipv4.ip_forward=1'
        backup: yes
      notify: Apply sysctl settings

    - name: Save iptables rules to foward between eth0 and wlan0
      ansible.builtin.copy:
        dest: /etc/iptables-restore.rules
        content: |
          iptables -t nat -A POSTROUTING -o wlan0 -j MASQUERADE
          iptables -A FORWARD -i wlan0 -o eth0 -m state --state RELATED,ESTABLISHED -j ACCEPT
          iptables -A FORWARD -i eth0 -o wlan0 -j ACCEPT
        backup: yes

    - name: Create systemd service for iptables-restore
      ansible.builtin.copy:
        dest: /etc/systemd/system/iptables-restore.service
        content: |
          [Unit]
          Description=Set iptables rules on startup for wlan0 and eth0 forwarding

          [Service]
          ExecStart=/sbin/iptables-restore < /etc/iptables-restore.rules
          Type=oneshot
          RemainAfterExit=yes

          [Install]
          WantedBy=multi-user.target
        owner: root
        group: root
        mode: '0644'

    - name: Enable and start iptables-restore service
      ansible.builtin.systemd:
        name: iptables-restore
        enabled: yes
        state: restarted
        daemon_reload: yes

  handlers:
    - name: Apply Netplan
      command: netplan apply

    - name: Restart DHCP Server
      service:
        name: isc-dhcp-server
        state: restarted
    
    - name: Apply sysctl settings
      command: sysctl --system
