---
- name: Install Helm and deploy Helm charts
  hosts: localhost, nodes
  become: true
  vars:
    helm_chart_name: "cilium"
    helm_release_name: "cilium"
    helm_namespace: "kube-system"

  roles:
    - role: helm
      helm_chart_repo: "https://helm.cilium.io/"

  tasks:
    - name: Install Cilium Helm chart - service mesh mode
      ansible.builtin.command:
        cmd: >
          helm install {{ helm_release_name }} cilium/{{ helm_chart_name }}
          --kubeconfig /etc/kubernetes/admin.conf
          --namespace {{ helm_namespace }}
          --set global.nodeinit.enabled=true
          --set global.kubeProxyReplacement=partial
          --set global.hostServices.enabled=false
          --set global.externalIPs.enabled=true
          --set global.nodePort.enabled=true
          --set global.bpf.masquerade=true
          --set global.tunnel=disabled
          --set global.loadBalancer.mode=hybrid
          --set global.proxy.enabled=true
          --set global.proxy.autoInject=true
          --set ipam.operator.clusterPoolIPv4PodCIDRList[0]=10.0.0.0/16
          --set ipam.operator.clusterPoolIPv4PodCIDR[0]=10.0.0.100/24
          --set ipam.operator.clusterPoolIPv4PodCIDR[1]=10.0.0.200/24