---
- name: Install and configure Kea DHCP server
  hosts: localhost
  become: true
  tasks:
    - name: Install Kea DHCP server
      apt:
        name: kea
        state: present

    - name: Create Kea user and group
      user:
        name: kea
        system: yes
        create_home: no

    - name: Create Kea configuration directory
      file:
        path: /etc/kea
        state: directory
        owner: kea
        group: kea
        mode: '0755'

    - name: Ensure lease file directory exists
      file:
        path: /var/lib/kea
        state: directory
        owner: kea
        group: kea
        mode: '0755'

    - name: Initialize lease file
      file:
        path: /var/lib/kea/dhcp4.leases
        state: touch
        owner: kea
        group: kea
        mode: '0644'

    - name: Configure Kea DHCP server
      copy:
        dest: /etc/kea/kea-dhcp4.conf
        content: |
          {
            "Dhcp4": {
              "interfaces-config": {
                "interfaces": [ "eth0" ]
              },
              "lease-database": {
                "type": "memfile",
                "persist": true,
                "name": "/var/lib/kea/dhcp4.leases"
              },
              "subnet4": [
                {
                  "subnet": "10.0.0.0/24",
                  "pools": [
                    { "pool": "10.0.0.2 - 10.0.0.10" }
                  ],
                  "option-data": [
                    { "name": "routers", "data": "10.0.0.1" },
                    { "name": "subnet-mask", "data": "255.255.255.0" }
                  ]
                }
              ]
            }
          }
        owner: kea
        group: kea
        mode: '0644'

    - name: Configure Kea DHCP server service to run as kea user
      lineinfile:
        path: /usr/lib/systemd/system/kea-dhcp4-server.service
        regexp: '^User='
        line: 'User=kea'
        create: yes
        backup: yes

    - name: Configure Kea DHCP server service group to run as kea group
      lineinfile:
        path: /usr/lib/systemd/system/kea-dhcp4-server.service
        regexp: '^Group='
        line: 'Group=kea'
        create: yes
        backup: yes

    - name: Reload systemd daemon
      command: systemctl daemon-reload

    - name: Enable and start Kea DHCP server
      systemd:
        name: kea-dhcp4-server
        enabled: yes
        state: started

  handlers:
    - name: Restart Kea DHCP server
      systemd:
        name: kea-dhcp4-server
        state: restarted