---
- name: Deploy Kubernetes
  hosts: localhost, nodes
  become: true
  vars:
    ansible_user: mchellmer

  tasks:
    # - name: clear docker sources
    #   file:
    #     path: "{{ item }}"
    #     state: absent
    #   with_items:
    #     - /usr/share/keyrings/docker.asc
    #     - /etc/apt/keyrings/docker.asc

    - name: Install additional packages
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
    
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Create /etc/apt/keyrings directory
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Docker's GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: Add Docker repo
      ansible.builtin.apt_repository:
        repo: "deb [arch=arm64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        update_cache: yes

    - name: Install containerd.io package
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: yes

    - name: Add user to the Docker group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Generate fresh containerd config
      shell: |
        rm /etc/containerd/config.toml
        containerd config default > /etc/containerd/config.toml

    - name: Set containerd cgroup to systemd
      replace:
        path: /etc/containerd/config.toml
        regexp: 'SystemdCgroup = true'
        replace: 'SystemdCgroup = false'

    - name: Restart containerd service
      systemd:
        name: containerd
        state: restarted