- name: Install Helm and deploy Helm charts
  hosts: localhost
  become: true
  vars:
    ansible_user: mchellmer
    helm_chart_name: "cilium"
    helm_release_name: "cilium"
    helm_namespace: "kube-system"

  roles:
    - role: helm
      helm_chart_repo: "https://helm.cilium.io/"

  tasks:
    - name: Check if become is working
      ansible.builtin.command:
        cmd: "whoami"
      register: become_check
      become: true

    - name: Debug become check
      ansible.builtin.debug:
        msg: "Running as user: {{ become_check.stdout }}"

    - name: Check if kubeconfig file exists
      ansible.builtin.stat:
        path: "/home/{{ ansible_user }}/.kube/config"
      register: kubeconfig_stat

    - name: Debug kubeconfig file existence
      ansible.builtin.debug:
        msg: "Kubeconfig file exists: {{ kubeconfig_stat.stat.exists }}"

    - name: Check kubeconfig file permissions
      ansible.builtin.command:
        cmd: "ls -l /home/{{ ansible_user }}/.kube/config"
      register: kubeconfig_permissions
      failed_when: false

    - name: Debug kubeconfig file permissions
      ansible.builtin.debug:
        msg: "Kubeconfig file permissions: {{ kubeconfig_permissions.stdout }}"

    - name: Output kubeconfig file contents
      ansible.builtin.command:
        cmd: "cat /home/{{ ansible_user }}/.kube/config"
      register: kubeconfig_contents
      failed_when: false

    - name: Debug kubeconfig file contents
      ansible.builtin.debug:
        msg: "Kubeconfig file contents: {{ kubeconfig_contents.stdout }}"

    - name: Install Cilium Helm chart - service mesh mode
      block:
        - name: Install Cilium Helm chart
          ansible.builtin.command:
            cmd: >
              helm install {{ helm_release_name }} cilium/{{ helm_chart_name }}
              --kubeconfig /home/{{ ansible_user }}/.kube/config
              --namespace {{ helm_namespace }}
              --set global.nodeinit.enabled=true
              --set global.kubeProxyReplacement=partial
              --set global.hostServices.enabled=false
              --set global.externalIPs.enabled=true
              --set global.nodePort.enabled=true
              --set global.bpf.masquerade=true
              --set global.tunnel=disabled
              --set global.loadBalancer.mode=hybrid
              --set global.proxy.enabled=true
              --set global.proxy.autoInject=true
              --set ipam.mode=cluster-pool
              --set ipam.operator.clusterPoolIPv4PodCIDRList[0]=10.0.1.0/25
          environment:
            KUBECONFIG: "/home/{{ ansible_user }}/.kube/config"
      rescue:
        - name: Delete Cilium Helm chart if installation fails
          ansible.builtin.command:
            cmd: >
              helm delete {{ helm_release_name }}
              --kubeconfig /home/{{ ansible_user }}/.kube/config
              --namespace {{ helm_namespace }}
          environment:
            KUBECONFIG: "/home/{{ ansible_user }}/.kube/config"