---
- name: Setup SSH keys
  hosts: localhost, master, worker
  vars:
    ansible_user: mchellmer
    ssh_key_path: "{{ ansible_user_dir }}/.ssh/id_rsa"
  tasks:
    - name: Generate SSH key pair on localhost
      openssh_keypair:
        path: "{{ ssh_key_path }}"
        force: True  # Change to True if you want to overwrite existing keys
      register: ssh_key
      delegate_to: localhost
      
    - name: Copy SSH public key from localhost to remote nodes
      copy:
        src: "{{ lookup('file', ssh_key_path) }}"
        dest: "/tmp/id_rsa.pub"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0644'

- name: Update and upgrade Ubuntu packages
  hosts: master, worker
  become: true
  vars:
    ansible_user: mchellmer
  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes

    - name: Update hosts with node maps
      lineinfile:
        path: /etc/hosts
        line: "{{ item.value }} {{ item.key }}"
        state: present
        backup: yes
      loop: "{{ k8s_hostnames | dict2items }}"

    - name: Install ssh key to nodes
      authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ lookup('file', '/tmp/id_rsa.pub') }}"

  roles:
    - role: k8s_iptables
  
  post_tasks:
  - name: Reboot nodes
    reboot:
      reboot_timeout: 30
    ignore_errors: yes