---
- name: Install and configure isc-dhcp-server and update iptables
  hosts: localhost
  become: true
  tasks:
    - name: Install isc-dhcp-server
      apt:
        name: isc-dhcp-server
        state: present

    - name: Update 50-cloud-init.yaml
      lineinfile:
        path: /etc/netplan/50-cloud-init.yaml
        regexp: '^(\s+)dhcp4:\strue$'
        line: '\1dhcp4: false'
        backup: yes
      notify:
        - Apply Netplan

    - name: Update dhcpd.conf
      template:
        src: dhcpd.conf.j2
        dest: /etc/dhcp/dhcpd.conf
        owner: root
        group: root
        mode: '0644'
      notify:
        - Restart DHCP Server

    - name: Create k8s.conf for sysctl
      template:
        src: k8s.conf.j2
        dest: /etc/sysctl.d/k8s.conf
        owner: root
        group: root
        mode: '0644'
      notify:
        - Apply Sysctl

    - name: Update rc.local for iptables
      lineinfile:
        path: /etc/rc.local
        line: '/sbin/iptables-restore < /etc/iptables/rules.v4'
        backup: yes
      notify:
        - Restart rc.local

  handlers:
    - name: Apply Netplan
      command: netplan apply

    - name: Restart DHCP Server
      service:
        name: isc-dhcp-server
        state: restarted

    - name: Apply Sysctl
      command: sysctl -p /etc/sysctl.d/k8s.conf

    - name: Restart rc.local
      command: systemctl restart rc-local
