---
- name: Deploy Flannel on Kubernetes
  hosts: master
  vars:
    ansible_user: mchellmer
  tasks:
    - name: Apply kube-flannel
      command: kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml {{ kubectl_args | default('') }}
      
#    - name: Apply kube-flannel from local template
#      template:
#        src: templates/kube-flannel.yaml.j2
#        dest: /tmp/kube-flannel.yaml
#
#    - name: Apply kube-flannel
#      command: kubectl apply -f /tmp/kube-flannel.yaml {{ kubectl_args | default('') }}