---
- name: Install and configure Kea DHCP server
  hosts: localhost
  become: true
  tasks:
    - name: Install Kea DHCP server
      apt:
        name: kea
        state: present

    - name: Create Kea configuration directory
      file:
        path: /etc/kea
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Configure Kea DHCP server
      copy:
        dest: /etc/kea/kea-dhcp4.conf
        content: |
          {
            "Dhcp4": {
              "interfaces-config": {
                "interfaces": [ "eth0" ]
              },
              "lease-database": {
                "type": "memfile",
                "persist": true,
                "name": "/var/lib/kea/dhcp4.leases"
              },
              "subnet4": [
                {
                  "subnet": "10.0.0.0/24",
                  "pools": [
                    { "pool": "10.0.0.2 - 10.0.0.10" }
                  ],
                  "option-data": [
                    { "name": "routers", "data": "10.0.0.1" },
                    { "name": "subnet-mask", "data": "255.255.255.0" }
                  ]
                }
              ]
            }
          }
        owner: root
        group: root
        mode: '0644'

    - name: Enable and start Kea DHCP server
      systemd:
        name: kea-dhcp4-server
        enabled: yes
        state: started

  handlers:
    - name: Restart Kea DHCP server
      systemd:
        name: kea-dhcp4-server
        state: restarted