name: Trigger GitLab CI/CD Pipeline

on:
  push:
    branches:
      - cicd  # or the branch you want to trigger the pipeline for

jobs:
  trigger_gitlab_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitLab Pipeline
        run: |
          curl --request POST \
          --form token=$GITLAB_TRIGGER_TOKEN \
          --form ref=main \
          https://gitlab.com/api/v4/projects/nineteenseventytwo-server/trigger/pipeline
        env:
          GITLAB_TRIGGER_TOKEN: ${{ secrets.GITLAB_TRIGGER_TOKEN }}
